"""Permutation test for the three primary outcomes (B3).

For LVEF, BNP, and Mean Gradient, the gold-standard null is generated by
shuffling the target column and recomputing ΔR² = R²_full − R²_baseline.
Empirical p-value = fraction of permutations with ΔR²_perm ≥ ΔR²_observed.

NOTE: This is computationally expensive (~3 h total on a typical laptop).
Skip in the sandbox; the user runs it on their own machine. Outputs:

  output/FigureS7_permutation_null.{png,pdf,svg}
  output/permutation_test_results.xlsx
  output/archived/permutation_v2_checkpoint.pkl   (resumable)
"""
import os, sys, pickle, time, warnings
warnings.filterwarnings("ignore")
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

from config import (
    OUT_DIR, CKPT_DIR, BASELINE_FEATURES, FULL_FEATURES,
    PRIMARY_OUTCOMES, TARGET_DISPLAY, N_PERM, RANDOM_STATE_PRIMARY, N_MIN,
)
from core import load_cohort, fit_catboost_oof
from figures import (
    apply_rcparams, black_box, cm, save_triplet, COL_RED, COL_DARKR, COL_GREY,
)

CKPT_PERM = os.path.join(CKPT_DIR, "permutation_v2_checkpoint.pkl")


def run_permutation_test(df, target, n_perm=N_PERM):
    """For one primary outcome: compute the observed ΔR² (full-vs-baseline)
    and 'n_perm' permutation-null ΔR² values."""
    df_sub = df.dropna(subset=FULL_FEATURES + [target])
    n = len(df_sub)
    if n < N_MIN: return None

    # Observed
    _, pb, _, _ = fit_catboost_oof(df_sub, BASELINE_FEATURES, target)
    y, pf, _, _ = fit_catboost_oof(df_sub, FULL_FEATURES,     target)
    obs = r2_score(y, pf) - r2_score(y, pb)

    rng = np.random.default_rng(RANDOM_STATE_PRIMARY)
    null = []
    for _ in range(n_perm):
        df_perm = df_sub.copy()
        df_perm[target] = rng.permutation(df_sub[target].values)
        _, pb_p, _, _ = fit_catboost_oof(df_perm, BASELINE_FEATURES, target)
        y_p, pf_p, _, _ = fit_catboost_oof(df_perm, FULL_FEATURES, target)
        null.append(r2_score(y_p, pf_p) - r2_score(y_p, pb_p))
    null = np.asarray(null)
    # Continuity correction: p = (k+1)/(N+1) so p is never exactly 0
    k = int((null >= obs).sum()); p_val = float((k + 1) / (len(null) + 1))
    return {"display": TARGET_DISPLAY[target], "n": int(n),
            "observed_delta_r2": float(obs), "null": null.tolist(),
            "p_perm": p_val}


def render_S7(state):
    apply_rcparams()
    fig, axes = plt.subplots(1, 3, figsize=(cm(5.8 * 3), cm(6.5)), squeeze=False)
    axes = axes.flatten()
    rows = []
    for ax, target in zip(axes, PRIMARY_OUTCOMES):
        r = state.get(target)
        if r is None:
            ax.text(0.5, 0.5, f"{TARGET_DISPLAY[target]}\nnot yet run",
                    ha='center', va='center', transform=ax.transAxes)
            ax.axis('off'); continue
        null = np.asarray(r["null"])
        ax.hist(null, bins=40, color=COL_GREY, edgecolor='black', linewidth=0.4)
        ax.axvline(r["observed_delta_r2"], color=COL_RED, linewidth=1.4,
                   label=f"Observed = {r['observed_delta_r2']:+.3f}")
        ax.set_xlabel(f"ΔR² under target permutation")
        ax.set_ylabel("Count")
        ax.set_title(r["display"])
        ax.text(0.04, 0.96,
                f"n = {r['n']:,}\n"
                f"p_perm = {r['p_perm']:.3g}\n"
                f"n_perm = {len(r['null'])}",
                transform=ax.transAxes, fontsize=7, va='top', ha='left')
        ax.legend(loc='upper right', fontsize=7, frameon=True,
                  edgecolor='black').get_frame().set_linewidth(0.8)
        black_box(ax)
        rows.append({"Target": r["display"], "N": r["n"],
                     "Observed_DeltaR2": r["observed_delta_r2"],
                     "p_perm": r["p_perm"], "n_perm": len(r["null"])})
    fig.suptitle(
        "Permutation null distribution of ΔR² for the three primary outcomes",
        fontsize=10, fontweight='bold')
    fig.tight_layout()
    save_triplet(fig, OUT_DIR, "FigureS7_permutation_null")
    if rows:
        pd.DataFrame(rows).to_excel(
            os.path.join(OUT_DIR, "permutation_test_results.xlsx"), index=False)


def run(n_perm=N_PERM):
    if os.path.exists(CKPT_PERM):
        with open(CKPT_PERM, "rb") as f: state = pickle.load(f)
    else:
        state = {}
    df = load_cohort()
    for target in PRIMARY_OUTCOMES:
        if target in state: continue
        print(f"\n── Permutation test for {TARGET_DISPLAY[target]} (n_perm={n_perm}) ──")
        t0 = time.time()
        r = run_permutation_test(df, target, n_perm=n_perm)
        state[target] = r
        with open(CKPT_PERM, "wb") as f: pickle.dump(state, f)
        if r is not None:
            print(f"  observed ΔR² = {r['observed_delta_r2']:+.3f}; "
                  f"p_perm = {r['p_perm']:.4g}; "
                  f"runtime = {time.time()-t0:.0f}s")
    render_S7(state)


if __name__ == "__main__":
    n_perm = int(sys.argv[1]) if len(sys.argv) > 1 else N_PERM
    run(n_perm)
